from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List
from uuid import uuid4

from models.business_action import BusinessAction


@dataclass
class CommerceDecision:
    """
    Standard decision proposal generated by an ACOS agent.
    """

    agent_id: str
    goal: str
    business_action: BusinessAction

    context: Dict[str, Any] = field(default_factory=dict)
    alternatives: List[BusinessAction] = field(default_factory=list)
    expected_benefit: Dict[str, float] = field(default_factory=dict)

    confidence: float = 0.0
    risk: float = 0.0
    evidence: List[str] = field(default_factory=list)

    negotiation_status: str = "PENDING"
    execution_status: str = "PENDING"
    learning_status: str = "PENDING"

    proposal_id: str = field(
        default_factory=lambda: str(uuid4())
    )

    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def __post_init__(self) -> None:
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("confidence must be between 0 and 1")

        if not 0.0 <= self.risk <= 1.0:
            raise ValueError("risk must be between 0 and 1")