from dataclasses import asdict, dataclass, field
from datetime import datetime
from typing import Any, Dict
from uuid import uuid4


@dataclass
class OptimizationRecommendation:
    """
    Represents an optimization recommendation generated by SCOE.

    A recommendation may target an agent, operation, strategy,
    or the complete ACOS system.
    """

    recommendation_type: str
    target: str
    message: str
    expected_benefit: float
    confidence: float

    recommendation_id: str = field(
        default_factory=lambda: f"REC-{uuid4().hex[:10].upper()}"
    )

    evidence: Dict[str, Any] = field(
        default_factory=dict
    )

    priority: str = "MEDIUM"

    created_at: datetime = field(
        default_factory=datetime.utcnow
    )

    def __post_init__(self) -> None:
        self.recommendation_type = (
            str(self.recommendation_type)
            .strip()
            .upper()
        )

        self.target = str(
            self.target
        ).strip()

        self.message = str(
            self.message
        ).strip()

        self.priority = (
            str(self.priority)
            .strip()
            .upper()
        )

        self.expected_benefit = self._clamp(
            float(self.expected_benefit),
            -1.0,
            1.0
        )

        self.confidence = self._clamp(
            float(self.confidence),
            0.0,
            1.0
        )

        valid_priorities = {
            "LOW",
            "MEDIUM",
            "HIGH",
            "CRITICAL"
        }

        if self.priority not in valid_priorities:
            raise ValueError(
                "priority must be one of: "
                "LOW, MEDIUM, HIGH, CRITICAL."
            )

        if not self.target:
            raise ValueError(
                "Recommendation target cannot be empty."
            )

        if not self.message:
            raise ValueError(
                "Recommendation message cannot be empty."
            )

    def is_positive(self) -> bool:
        return self.expected_benefit > 0.0

    def is_high_priority(self) -> bool:
        return self.priority in {
            "HIGH",
            "CRITICAL"
        }

    def to_dict(self) -> dict:
        data = asdict(self)

        data["created_at"] = (
            self.created_at.isoformat()
        )

        return data

    @staticmethod
    def _clamp(
        value: float,
        minimum: float,
        maximum: float
    ) -> float:
        return max(
            minimum,
            min(value, maximum)
        )