from dataclasses import asdict, dataclass, field
from datetime import datetime
from typing import Any, Dict, List

from models.optimization_recommendation import (
    OptimizationRecommendation
)


@dataclass
class SystemOptimizationReport:
    """
    Complete output generated by the
    Self-Commerce Optimization Engine.
    """

    system_health_score: float
    system_health_status: str

    agent_rankings: List[Dict[str, Any]] = field(
        default_factory=list
    )

    strong_agents: List[str] = field(
        default_factory=list
    )

    weak_agents: List[str] = field(
        default_factory=list
    )

    best_operations: List[Dict[str, Any]] = field(
        default_factory=list
    )

    weak_operations: List[Dict[str, Any]] = field(
        default_factory=list
    )

    business_patterns: List[Dict[str, Any]] = field(
        default_factory=list
    )

    recommendations: List[
        OptimizationRecommendation
    ] = field(
        default_factory=list
    )

    generated_at: datetime = field(
        default_factory=datetime.utcnow
    )

    def __post_init__(self) -> None:
        self.system_health_score = self._clamp(
            float(self.system_health_score),
            0.0,
            1.0
        )

        self.system_health_status = (
            str(self.system_health_status)
            .strip()
            .upper()
        )

    @property
    def recommendation_count(self) -> int:
        return len(
            self.recommendations
        )

    def get_high_priority_recommendations(
        self
    ) -> List[OptimizationRecommendation]:
        return [
            recommendation
            for recommendation in self.recommendations
            if recommendation.is_high_priority()
        ]

    def to_dict(self) -> dict:
        data = asdict(self)

        data["recommendations"] = [
            recommendation.to_dict()
            for recommendation in self.recommendations
        ]

        data["generated_at"] = (
            self.generated_at.isoformat()
        )

        return data

    @staticmethod
    def _clamp(
        value: float,
        minimum: float,
        maximum: float
    ) -> float:
        return max(
            minimum,
            min(value, maximum)
        )